### ISSUE TITLE
Finish initial arfc draft of Moltres introduction manuscript

### ISSUE THREAD

**Issue by lindsayad** [arfc/publications#6]
### Tasks

- [x] Decide whether we want to submit a JOSS paper first
- [x] Adding some comparison with expected results will be necessary. Ideally, MSRE or 1-D analytical solutions. Are the fluxes the appropriate magnitude? How correct is the peak/average flux ratio? Is the temperature profile as was seen in MSRE?
- [x] Performance analysis. It runs fast, but how fast? Is it appropriate to do a scaling study?
- [x] Add description of how the group constants were generated for this particular simulation.

More to be added through comments.

Tag @katyhuff

**Comment by katyhuff** [comment]
Adding some comparison with expected results will be necessary. Ideally, MSRE or 1-D analytical solutions. Are the fluxes the appropriate magnitude? How correct is the peak/average flux ratio? Is the temperature profile as was seen in MSRE?

**Comment by katyhuff** [comment]
Maybe also some more performance analysis detail.

**Comment by lindsayad** [comment]
What are you thinking about JOSS?

**Comment by katyhuff** [comment]
We should definitely publish it in JOSS. Needs some attributes to be
qualified. This is how we evaluate them:
http://joss.theoj.org/about#reviewer_guidelines .

So, tests, docs, install instructions, etc.

**Comment by lindsayad** [comment]
### Nestor, MSRE preliminary physics report (calculations):
- 8% fuel salt volume fraction (final design 22.5 %)
- 1 mole% UF4
- 93% U235 enrichment
- average thermal flux = 2.9x10^13 nts/cm^2
- peak thermal flux = 7.3x10^13 nts/cm^2
- ratio = 2.5
- average core power density = 4 W/cm^3
- peak core power density = 10 W/cm^3

### Ours:
- 22.5% fuel salt volume fraction
- .9 mole% UF4
- 33% U235 enrichment
- average thermal flux = 1.0x10^13 nts/cm^2
- peak thermal flux = 2.3x10^13 nts/cm^2
- ratio =  2.3
- peak core power density = 17 W/cm^3

Really finding very little experimental data, but it must exist

**Comment by lindsayad** [comment]
@katyhuff What would a scaling study look like?

**Comment by katyhuff** [comment]
Typically, I see the following:

A very simple problem (specific materials, geometry, number of timesteps) is run with with a certain number of degrees of freedom (e.g. mesh resolution). Then, you investigate how quickly the problem runs when you spread that problem across an increasing number of processors. You want to see a strong decrease in runtime as the number of processors increases.  

Considering the things that might impact scaling, the modeler (you) will often choose a couple of different canonical small simple problems which demonstrate the bounds of scaling behavior. For example (just an example), if you know that the scaling is 'bad' for problems with asymmetric geometries, you might run your scaling study with two different problems -- one sphere and one complex/asymmetric structure. Then, you would plot the scaling results together, to communicate that you expect most problems will fall between these scaling behavioral trends.

Here are two good examples:
http://www.sciencedirect.com/science/article/pii/S0927025611004204 
http://www.sciencedirect.com/science/article/pii/S0022311512000165

**Comment by katyhuff** [comment]
you've finished this draft! thanks @lindsayad !!! 

![bitmoji](https://render.bitstrips.com/v2/cpanel/10188118-116454032_15-s1-v1.png?transparent=1&palette=1&width=246)
